use std::{env, fs, path::PathBuf};

use serde_json::{Map, Value};

const CLI_HELP_JSON: &str = "src/cli-help.json";
const FLAKE_LOCK_JSON: &str = "../../../flake.lock";
const LITELLM_PRICING_JSON: &str = "model_prices_and_context_window.json";
const OUT_PRICING_JSON: &str = "litellm-pricing.json";
const PRICING_JSON_PATH_ENV: &str = "CCUSAGE_PRICING_JSON_PATH";
const PRICING_FETCH_TIMEOUT_SECONDS: u64 = 10;

fn main() {
    println!("cargo:rerun-if-changed={CLI_HELP_JSON}");
    println!("cargo:rerun-if-env-changed={PRICING_JSON_PATH_ENV}");

    generate_cli_help_rs();

    let out_path = out_dir_path(OUT_PRICING_JSON);
    let pricing_json = if let Some(path) = env::var_os(PRICING_JSON_PATH_ENV) {
        let path = PathBuf::from(path);
        println!("cargo:rerun-if-changed={}", path.display());
        fs::read_to_string(path).expect("read pricing snapshot from CCUSAGE_PRICING_JSON_PATH")
    } else {
        println!("cargo:rerun-if-changed={FLAKE_LOCK_JSON}");
        fetch_pricing_json().expect("fetch LiteLLM pricing for embed")
    };
    let pricing_json = compact_pricing_json(&pricing_json).expect("compact LiteLLM pricing JSON");

    fs::write(out_path, pricing_json).expect("write build-time pricing snapshot");
}

fn out_dir_path(file_name: &str) -> PathBuf {
    PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo")).join(file_name)
}

fn generate_cli_help_rs() {
    let source = fs::read_to_string(CLI_HELP_JSON).expect("read CLI help spec");
    let Value::Object(option_sets) =
        serde_json::from_str::<Value>(&source).expect("parse CLI help spec")
    else {
        panic!("CLI help spec must be a JSON object");
    };

    let mut output = String::from("// @generated by build.rs\n\n");
    let mut option_sets = option_sets.iter().collect::<Vec<_>>();
    option_sets.sort_by(|(left, _), (right, _)| left.cmp(right));
    for (function_name, options) in option_sets {
        let rendered = render_options(options);
        output.push_str(&format!(
            "fn {function_name}() -> &'static str {{\n    {}\n}}\n\n",
            rust_string_literal(&rendered)
        ));
    }
    fs::write(out_dir_path("cli-help.rs"), output).expect("write generated CLI help");
}

fn render_options(options: &Value) -> String {
    let Value::Array(options) = options else {
        panic!("CLI help option set must be an array");
    };
    let width = options
        .iter()
        .map(|option| {
            let Value::Object(option) = option else {
                panic!("CLI help option must be an object");
            };
            string_field(option, "flags").len()
        })
        .max()
        .unwrap_or(36)
        .max(36);
    let mut lines = vec!["OPTIONS:".to_string()];
    for option in options {
        let Value::Object(option) = option else {
            panic!("CLI help option must be an object");
        };
        let flags = string_field(option, "flags");
        let description = string_field(option, "description");
        let mut line = format!("  {flags:<width$} {description}");
        let mut details = Vec::new();
        if let Some(default) = optional_string_field(option, "default") {
            details.push(format!("default: {default}"));
        }
        if let Some(choices) = option.get("choices") {
            let Value::Array(choices) = choices else {
                panic!("CLI help choices must be an array");
            };
            if !choices.is_empty() {
                details.push(format!(
                    "choices: {}",
                    choices
                        .iter()
                        .map(|choice| {
                            choice
                                .as_str()
                                .expect("CLI help choice must be a string")
                                .to_string()
                        })
                        .collect::<Vec<_>>()
                        .join(" | ")
                ));
            }
        }
        if !details.is_empty() {
            line.push_str(&format!(" ({})", details.join(", ")));
        }
        lines.push(line);
    }
    lines.join("\n")
}

fn string_field(object: &Map<String, Value>, field: &str) -> String {
    optional_string_field(object, field).unwrap_or_else(|| panic!("missing CLI help field {field}"))
}

fn optional_string_field(object: &Map<String, Value>, field: &str) -> Option<String> {
    object.get(field).map(|value| {
        value
            .as_str()
            .unwrap_or_else(|| panic!("CLI help field {field} must be a string"))
            .to_string()
    })
}

fn rust_string_literal(value: &str) -> String {
    serde_json::to_string(value).expect("encode Rust string literal")
}

fn fetch_pricing_json() -> std::io::Result<String> {
    let response = minreq::get(litellm_pricing_url()?)
        .with_timeout(PRICING_FETCH_TIMEOUT_SECONDS)
        .send()
        .map_err(|error| std::io::Error::other(error.to_string()))?;
    if response.status_code != 200 {
        return Err(std::io::Error::other(format!(
            "HTTP {}",
            response.status_code
        )));
    }
    Ok(response
        .as_str()
        .map_err(|error| std::io::Error::new(std::io::ErrorKind::InvalidData, error.to_string()))?
        .to_string())
}

fn litellm_pricing_url() -> std::io::Result<String> {
    let flake_lock = fs::read_to_string(FLAKE_LOCK_JSON)?;
    let Value::Object(root) = serde_json::from_str::<Value>(&flake_lock)
        .map_err(|error| std::io::Error::new(std::io::ErrorKind::InvalidData, error.to_string()))?
    else {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            "flake.lock must be a JSON object",
        ));
    };
    let locked = root
        .get("nodes")
        .and_then(|nodes| nodes.get("litellm"))
        .and_then(|litellm| litellm.get("locked"))
        .and_then(Value::as_object)
        .ok_or_else(|| {
            std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "flake.lock is missing nodes.litellm.locked",
            )
        })?;
    let owner = required_flake_lock_string_field(locked, "owner")?;
    let repo = required_flake_lock_string_field(locked, "repo")?;
    let rev = required_flake_lock_string_field(locked, "rev")?;

    Ok(format!(
        "https://raw.githubusercontent.com/{owner}/{repo}/{rev}/{LITELLM_PRICING_JSON}"
    ))
}

fn required_flake_lock_string_field(
    object: &Map<String, Value>,
    field: &str,
) -> std::io::Result<String> {
    object
        .get(field)
        .and_then(Value::as_str)
        .map(str::to_string)
        .ok_or_else(|| {
            std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("flake.lock nodes.litellm.locked.{field} must be a string"),
            )
        })
}

fn compact_pricing_json(json: &str) -> Option<String> {
    let Value::Object(raw) = serde_json::from_str::<Value>(json).ok()? else {
        return None;
    };
    let mut compact = Map::new();
    for (model, pricing) in raw {
        if !is_embedded_model(&model) {
            continue;
        }
        let Value::Object(pricing) = pricing else {
            continue;
        };
        let mut fields = Map::new();
        for field in [
            "input_cost_per_token",
            "output_cost_per_token",
            "cache_creation_input_token_cost",
            "cache_read_input_token_cost",
            "input_cost_per_token_above_200k_tokens",
            "output_cost_per_token_above_200k_tokens",
            "cache_creation_input_token_cost_above_200k_tokens",
            "cache_read_input_token_cost_above_200k_tokens",
            "max_input_tokens",
            "provider_specific_entry",
        ] {
            let Some(value) = pricing.get(field) else {
                continue;
            };
            if !value.is_null() {
                fields.insert(field.to_string(), value.clone());
            }
        }
        if fields.contains_key("input_cost_per_token")
            && fields.contains_key("output_cost_per_token")
        {
            compact.insert(model, Value::Object(fields));
        }
    }
    serde_json::to_string(&Value::Object(compact)).ok()
}

fn is_embedded_model(model: &str) -> bool {
    model.starts_with("claude-")
        || model.starts_with("anthropic.")
        || model.starts_with("anthropic/")
        || model.starts_with("us.anthropic.")
        || model.starts_with("eu.anthropic.")
        || model.starts_with("global.anthropic.")
        || model.starts_with("jp.anthropic.")
        || model.starts_with("au.anthropic.")
        || model.starts_with("gpt-")
        || model.starts_with("openai/")
        || model.starts_with("azure/")
        || model.starts_with("openrouter/openai/")
}
