packages:
  - .
  - docs

enablePrePostScripts: true
catalogMode: strict

catalogs:
  # Build tools and deployment
  build:
    '@oxc-project/runtime': ^0.82.1
    clean-pkg-json: ^1.3.0
    publint: ^0.3.12
    sort-package-json: ^3.4.0
    tsdown: ^0.14.1
    unplugin-macros: ^0.17.2
    unplugin-unused: ^0.5.1
    wrangler: ^4.30.0

  # Development tools and linting
  dev:
    '@antfu/ni': ^25.0.0
    '@mizchi/lsmcp': ^0.9.4
    '@praha/byethrow-mcp': ^0.1.2
    '@ryoppippi/eslint-config': ^0.3.7
    '@typescript/native-preview': ^7.0.0-dev.20250816.1
    bumpp: ^10.2.3
    eslint: ^9.33.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.5

  # Documentation tools
  docs:
    '@ryoppippi/vite-plugin-cloudflare-redirect': jsr:@ryoppippi/vite-plugin-cloudflare-redirect@^1.1.2
    typedoc: ^0.28.10
    typedoc-plugin-markdown: ^4.8.1
    typedoc-vitepress-theme: ^1.1.2
    vitepress: ^1.6.4
    vitepress-plugin-group-icons: ^1.6.3
    vitepress-plugin-llms: ^1.7.3
    vitepress-plugin-mermaid: ^2.0.17

  # Runtime libraries and utilities
  library:
    '@antfu/utils': ^9.2.0
    '@core/errorutil': jsr:^1.2.1
    '@hono/mcp': ^0.1.0
    '@hono/node-server': ^1.18.2
    '@modelcontextprotocol/sdk': ^1.17.3
    '@praha/byethrow': ^0.6.3
    '@ryoppippi/limo': jsr:^0.2.3
    '@std/async': jsr:^1.0.14
    ansi-escapes: ^7.0.0
    cli-table3: ^0.6.5
    consola: ^3.4.2
    es-toolkit: ^1.39.9
    fast-sort: ^3.4.1
    get-stdin: ^9.0.0
    gunshi: ^0.26.3
    hono: ^4.9.2
    nano-spawn: ^1.0.2
    path-type: ^6.0.0
    picocolors: ^1.1.1
    pretty-ms: ^9.2.0
    string-width: ^7.2.0
    tinyglobby: ^0.2.14
    type-fest: ^4.41.0
    xdg-basedir: ^5.1.0
    zod: ^3.25.67

  # Testing utilities
  test:
    fs-fixture: ^2.8.1
    vitest: ^3.2.4

  # TypeScript types
  types:
    '@types/bun': ^1.2.20
