[env]
SQLITE_OMIT_AUTHORIZATION = "1"
SQLITE_OMIT_AUTOMATIC_INDEX = "1"
SQLITE_OMIT_AUTOVACUUM = "1"
SQLITE_OMIT_BETWEEN_OPTIMIZATION = "1"
SQLITE_OMIT_BLOB_LITERAL = "1"
SQLITE_OMIT_CAST = "1"
SQLITE_OMIT_CASE_SENSITIVE_LIKE_PRAGMA = "1"
SQLITE_OMIT_CHECK = "1"
SQLITE_OMIT_COMPILEOPTION_DIAGS = "1"
SQLITE_OMIT_COMPLETE = "1"
SQLITE_OMIT_COMPOUND_SELECT = "1"
SQLITE_OMIT_DECLTYPE = "1"
SQLITE_OMIT_DEPRECATED = "1"
SQLITE_OMIT_DESERIALIZE = "1"
SQLITE_OMIT_EXPLAIN = "1"
SQLITE_OMIT_FLAG_PRAGMAS = "1"
SQLITE_OMIT_FOREIGN_KEY = "1"
SQLITE_OMIT_GENERATED_COLUMNS = "1"
SQLITE_OMIT_GET_TABLE = "1"
SQLITE_OMIT_HEX_INTEGER = "1"
SQLITE_OMIT_INCRBLOB = "1"
SQLITE_OMIT_INTEGRITY_CHECK = "1"
SQLITE_OMIT_INTROSPECTION_PRAGMAS = "1"
SQLITE_OMIT_JSON = "1"
SQLITE_OMIT_LIKE_OPTIMIZATION = "1"
SQLITE_OMIT_LOAD_EXTENSION = "1"
SQLITE_OMIT_LOCALTIME = "1"
SQLITE_OMIT_LOOKASIDE = "1"
SQLITE_OMIT_MEMORYDB = "1"
SQLITE_OMIT_OR_OPTIMIZATION = "1"
SQLITE_OMIT_PARSER_TRACE = "1"
SQLITE_OMIT_POPEN = "1"
SQLITE_OMIT_PROGRESS_CALLBACK = "1"
SQLITE_OMIT_QUICKBALANCE = "1"
SQLITE_OMIT_RANDOMNESS = "1"
SQLITE_OMIT_SCHEMA_PRAGMAS = "1"
SQLITE_OMIT_SCHEMA_VERSION_PRAGMAS = "1"
SQLITE_OMIT_SHARED_CACHE = "1"
SQLITE_OMIT_SHUTDOWN_DIRECTORIES = "1"
SQLITE_OMIT_TCL_VARIABLE = "1"
SQLITE_OMIT_TEST_CONTROL = "1"
SQLITE_OMIT_TRACE = "1"
SQLITE_OMIT_TRUNCATE_OPTIMIZATION = "1"
SQLITE_OMIT_TWOSIZE_LOOKASIDE = "1"
SQLITE_OMIT_UPSERT = "1"
SQLITE_OMIT_UTF16 = "1"
SQLITE_OMIT_XFER_OPT = "1"
